services:
  app:
    build: .
    container_name: markdown_blog_next
    environment:
      MONGODB_URI: mongodb://root:rootpass@mongo:27017/admin?retryWrites=true&w=majority
    ports:
     - 3000:3000
    depends_on:
      - mongo
 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
